### ISSUE TITLE
Checkins not possible in some countries (e.g. AT, CH, GB, FR, ...)

### ISSUE THREAD

**Issue by Lukas264** [Traewelling/traewelling#3338]
### Beschreibe das Problem

Seit dem Umstellen auf den neuen Fahrplanprovider ist es in vielen Teilen Österreichs nicht mehr möglich, in Züge des Nahverkehrs einzuchecken.
Bitte dringend Beheben!

### Was hast du Schritt für Schritt gemacht, bevor der Fehler auftrat?

Website geöffnet
Gewünschten Bahnhof gesucht

### Was hast du erwartet?

Nahverkehrszüge

### Browser-Konsole oder Fehlermeldungen (optional)

```bash

```

**Comment by MrKrisKrisu** [comment]
Transitous hat auch Daten für Österreich. Diese filtern wir gerade aber aus Lizenztechnischen Gründen raus.

Wir müssen uns da ein paar Kleinigkeiten noch in den nächsten Tagen/Wochen mal anschauen.

**Comment by Altonss** [comment]
This PR https://github.com/public-transport/transitous/pull/1064 at Transitous should greatly improve the situation for FR :)

**Comment by EratoNysiad** [comment]
Also trains in the Netherlands are missing.

**Comment by jjasloot** [comment]
> Also trains in the Netherlands are missing.

The api used (ovapi) does not specify a license for the data that is one of the recognized formal license. The readme does say that "You are free to use this data, but there is no service level agreement (best-effort) nor are you allowed to say you represent or impersonate any of the transit agencies listed here." (http://gtfs.ovapi.nl/README)

I emailed the ovapi e-mail address asking for clarification on the license so we can update this.

**Comment by RobinLinde** [comment]
As far as I can tell , it should be CC-0 which is also listed on the summary of available data on [openOV](https://openov.nl/#zakelijk) (somewhere at the bottom of the page). In the case that there's no response to the e-mail, [Google Groups](https://groups.google.com/g/openov/) might work.

**Comment by HerrLevin** [comment]
I've added the licenses for CH, AT, DK, IS, GB (most of it) manually to our database, a few more licenses in #3384 and thanks to @Altonss we also have FR. :)

My current solution for NL: Since they officially state that everyone can use their data as long as they're not impersonated, I've added a "Data source: OVapi.nl". This should be sufficient imho.

PS: If you find a data provider in https://api.transitous.org/gtfs/license.json that's currently not activated by us but has a sufficient license, please point us into the right direction of the license data, so that we can activate it in the next couple of days/weeks.

**Comment by Altonss** [comment]
The license of DK has been added in https://github.com/transitland/transitland-atlas/pull/1509, so this should become active without the need for manual override :)

**Comment by dancojocaru2000** [comment]
BE: De Lijn's [license agreement](https://data.delijn.be/content/Licentie%20voor%20gratis%20hergebruik%20_opendata%20portaal_2024.pdf) found on the [Open Data Portal](https://data.delijn.be/) seems to be a custom but free (as in freedom) license, with the only reason for making a custom license seemingly being references to Flemish law.

The main requirement for compliance seems to be specifying "Source: De Lijn".

**Comment by Jeder321** [comment]
Koleje Dolnośląskie (and many other polish train operators [some are not included in transitious data, yet], outside of PKP Intercity and Polregio, however PKPIC international trains curiously end on the first foreign station) are not included right now either. License for Koleje Dolnośląskie GTFS is also "custom", at least according to Transitious where they link to [Conditions for using Open Data](https://www.kolejedolnoslaskie.4bip.pl/upload/20200527103018iakfl5ggugya.pdf), however KD themselves states on their [GTFS page (in polish)](https://kolejedolnoslaskie.pl/rozklady-gtfs/) that "The static timetables are provided free of charge for an indefinite period and their use does not require prior notification or separate consent.", while using GTFS-RT requires specifying the source (Koleje Dolnośląskie) and last update time. 
Koleje Mazowieckie is not activated either and it does have [listed similar terms of using open data](https://bip.mazowieckie.com.pl/pl/ponowne-wykorzystywanie-informacji-sektora-publicznego) (differently worded but it's still the same thing) to KD, at least after skimming it.
Koleje Małopolskie is not activated, has no license listed whatsoever, their "open data" website does have [terms of use](https://bip.malopolska.pl/malopolskiekoleje,m,385286,dostep-do-informacji-publicznych.html) which come down to the same thing
Safe to say every polish source in license.json with "custom" license (or just lacking it, in case of some sources from mkuran.pl, which have CC0 listed on website? 🥴) is just yet another open data terms of use document coming down to the same thing. I am actually not aware of any proper license used by polish entities, maybe outside of GZM where they did specify CC-BY 4.0.

**Comment by aussiger** [comment]
I also have a question regarding the data source.

Right now, there are no trains or connection in the Czech Republic, despite the fact that they are on Transitious.

I can check in only on few international trains and in every mean of transport of the South Moravian region. On Sunday, I was able to see the public transport in Prague for like 5 minutes... until it dissapeared.

Are the other timetables planned to be added?

**Comment by jjasloot** [comment]
PID ("Pražská integrovaná doprava") data should be CC-BY 4.0 as per https://pid.cz/o-systemu/opendata/  but doesn't have that specified at the moment

For the Czech national traindata (CZPTT) I can't find a license for the data being used.

**Comment by HerrLevin** [comment]
@jjasloot Thank you! I've activated PID in our backend.

**Comment by aussiger** [comment]
Thank you very much for enabling the PID!

I did some research about the source of Czech National traindata and so far I found only one article on our Ministry of Transport website (https://md.gov.cz/Dokumenty/Verejna-doprava/Jizdni-rady,-kalendare-pro-jizdni-rady,-metodi-(1)/Jízdní-řady-veřejné-dopravy) that the "source is available for commercial and non commercial use". Not sure if that's helpful, but I'll search more later. 

EDIT: Valid link: https://md.gov.cz/Dokumenty/Verejna-doprava/Jizdni-rady,-kalendare-pro-jizdni-rady,-metodi-%281%29/Jizdni-rady-verejne-dopravy

> Podmínky užití dat CIS JŘ
Ministerstvo dopravy vede Celostátní informační systém o jízdních řádech pro potřeby veřejnosti. Data zveřejněna prostřednictvím tohoto systému jsou veřejně přístupná pro nekomerční i komerční použití.

**Comment by Lach-anonym** [comment]
I'm bumping the question of clarifying the situation of Polish (and not only) railway carrier/transport agency licenses - if they state approximately the same conditions of usage as in CC licenses (incl. requirement of attribution), then I think it shouldn't be a legal issue to activate the feeds, even manually.

Also another case - some French feeds (incl. IDFM) are licensed under Licence Mobilités (https://wiki.lafabriquedesmobilites.fr/wiki/Licence_Mobilit%C3%A9s), which is based on ODbL, but apparently has some reservations for transport agencies. Is it still an open license that can be added to the list?

**Comment by denisebitca** [comment]
In regards to the License Mobilités, if I understand it right, it has the same conditions as the ODbL, but includes:

- a clause about needing to be identifiable by the licenser upon request (you either can provide a first and last name + email or phone number if you are a person, or a company name, first and last name of the person responsible for using the data set and a French SIREN number* if you are a company)
- a clause stating the licenser can request financial compensation if requests to the dataset excede a certain limit (more than 720 requests a day or 30 requests an hour, as per French law: https://www.legifrance.gouv.fr/codes/id/LEGISCTA000042872038/2020-12-31)
- a small clause in the license that requires the licensee to inform the licenser when they redistribute part of the dataset to a third party, and if the licenser has not said anything in 30 days, the license is to be assumed to be granted to the third party (not so sure about this part)
- a clause stating the licensee cannot use the dataset to act against the interests of the French government's mobility strategy

That is rough, especially for the IDFM dataset.

*the writers of the license acknowledge on that wiki page @Lach-anonym linked to that for foreign companies who don't have such a number, it would be settled on a case by case basis

**Comment by ExoSkye** [comment]
From what I can tell, *some* British trains don't show up, but not all

When it comes to the UK, I believe it'd be far better if Traewelling implements direct support for the National/NetworkRail APIs, such as Darwin, since they exist, have afaik clear licensing, and are going to be far more accurate than any third party API since these are literally what are used, for example, for passenger information boards

More information about Darwin can be found here: https://wiki.openraildata.com/index.php/NRE_Darwin_Web_Service_(Public)

and in general on https://wiki.openraildata.com - this site is a treasure trove for the Open NR APIs

Failing this, https://realtimetrains.com also has a fairly decent and easy to use API afaik, which you can find here: https://api.rtt.io/

**Comment by Altonss** [comment]
Data for Flix and BlaBlaCar Bus should be available in Europe now :)

**Comment by maltechx** [comment]
The source of the Romanian Railways https://github.com/jbruechert/data.gov.ro-gtfs-exporter uses data from the open data portal: https://data.gov.ro/en/organization/sc-informatica-feroviara-sa. 

They specify either CC-BY 4.0 or OGL-ROU-1.0 as license.

**Comment by Lach-anonym** [comment]
~~I've emailed the Ministry of Regional Affairs and Agriculture of Estonia about their license of peatus.ee feed. The response is:~~
> Hello
> Our page publishes route data that is public. Bus route data is available from the page peatus.ee/gtfs. We have used the code to create the page: https://github.com/HSLdevcom

~~Thus I think it's a good idea to force activate the license for this source.~~ should be fixed soon

**Comment by Lach-anonym** [comment]
According to the website https://otwartedane.erzeszow.pl/dataset/rozklady-jazdy-gtfs/resource/956, the Mikołaj Kuranowski's ZTM Rzeszów data are on an open license.

**Comment by jjasloot** [comment]
### Spain

For Spain the official datasource for almost all sources is https://nap.transportes.gob.es/. Their license page (https://nap.transportes.gob.es/licencia-datos) seems pretty open, requiring attribution (Powered by MITRAMS with a link to the main page).

This license covers all the sources in https://github.com/public-transport/transitous/blob/main/feeds/es.json, **except** the `Trasnportes-Insular-de-La-Palma-(TILP)` .

The GTFS-RT feed for 'Ferrocarriles-de-la-Generalitat-de-Cataluña' is covered by 'cc-by' (https://dadesobertes.fgc.cat/explore/dataset/trip-updates-gtfs_realtime/information/)

### Italy
The data for 'Trenord' (it_Lombardia-Trenord.gtfs.zip) is covered by CC-BY 4.0, https://www.dati.lombardia.it/Mobilit-e-trasporti/Orario-Ferroviario-Regionale-Gtfs/3z4k-mxz9/about_data

**Comment by Lach-anonym** [comment]
~~The feed from SĮ "Susisiekimo paslaugos" (Vilnius) is also licensed on "give attribution, free usage" rules~~ should be fixed soon
https://judu.lt/atviri-duomenys/

**Comment by kasmar00** [comment]
For Poland most of the sources have a lengthy document instead of a license but looking at a couple:
- Warszawa essentially states that it gives permission to use the data and doesn't give any requirements (other than a good practice that applications using the data be free of charge): https://www.ztm.waw.pl/pliki-do-pobrania/dane-rozkladowe/

    > ZTM udostępniając dane udziela jednocześnie zgody na:
    > - wykorzystanie danych przez podmiot,

- Koleje Mazowieckie requires to give the datasource (traewelling already does that) and timestamp of data creation and data retrieval (I guess that's either something missing on transitous side or just current time): https://bip.mazowieckie.com.pl/pl/ponowne-wykorzystywanie-informacji-sektora-publicznego
- ZTM Poznań has the same requirements as above: https://www.ztm.poznan.pl/otwarte-dane/dla-deweloperow
- PKP Szybka Kolej Miejska w Trójmieście Sp. z o.o. has the same requirement: https://bip.skm.pkp.pl/otwarte-dane

So while they don't specify a specific open license, I think there's no problem with enabling them.

**Comment by Jeder321** [comment]
Bumping the issue regarding Koleje Mazowieckie, seems it's still not activated

**Comment by Lach-anonym** [comment]
Apparently this and other issue threads are ignored, so data activation requests for each feed should be in separate issues according to the scheme provided at https://help.traewelling.de/en/features/timetable/licensing/

(I mean it in good intention, as it will make the issue checking easier)

**Comment by MrKrisKrisu** [comment]
> separate issues

Yes, please. I'll close this issue to prevent confusion. Please keep new Issues small, use the template and don't put too many sources in one issue, so it can be resolved fast.
